const express = require('express');
const router = express.Router();
const demoAgent = require('../config/demoAgent');
const x402Auth = require('../middleware/x402Auth');
const githubService = require('../services/github');
const llmService = require('../services/llm');

// Protected MCP Endpoint for the agent
router.post('/:agentId/mcp', x402Auth, async (req, res) => {
  const { agentId } = req.params;
  const { method, params } = req.body;

  // Ensure they are calling our persistent demo agent
  if (agentId !== demoAgent.id) {
    return res.status(404).json({ error: "Agent not found" });
  }

  // Handle standard MCP methods
  switch (method) {
    case 'initialize':
      return res.status(200).json({
        serverInfo: { name: demoAgent.name, version: "1.0.0" },
        capabilities: demoAgent.capabilities
      });

    case 'tools/list':
      return res.status(200).json({
        tools: [
          { 
            name: "fix_github_issue", 
            description: "Clones repo, fixes the specified issue, and submits a Pull Request." 
          }
        ]
      });

    case 'tools/call':
      // Because it passed the x402Auth middleware, we know they paid!
      try {
        const { owner, repo, issueNumber, filePath } = params;
        
        if (!owner || !repo || !issueNumber || !filePath) {
          return res.status(400).json({ error: "Missing required parameters (owner, repo, issueNumber, filePath)" });
        }

        console.log(`🔧 Executing tool: fix_github_issue for ${owner}/${repo}#${issueNumber}`);

        // 1. Fetch Issue Description
        const issue = await githubService.getIssue(owner, repo, issueNumber);
        
        // 2. Fetch Target File Content
        const fileData = await githubService.getFileContent(owner, repo, filePath);
        
        // 3. Generate Code Fix using LLM
        const patchedCode = await llmService.generateCodeFix(issue.body, fileData.content, filePath);
        
        // 4. Create a new branch
        const branchName = `bountyfix/issue-${issueNumber}-${Date.now()}`;
        await githubService.createBranch(owner, repo, 'main', branchName);
        
        // 5. Commit the fix
        await githubService.commitFile(owner, repo, branchName, filePath, patchedCode, `Fix issue #${issueNumber}`, fileData.sha);
        
        // 6. Open a Pull Request
        const pr = await githubService.createPullRequest(
          owner, 
          repo, 
          branchName, 
          'main', 
          `Fix: Resolve Issue #${issueNumber}`, 
          `This PR was autonomously generated by BountyFix to resolve #${issueNumber}.\n\nWhen you merge this PR, the OKX.AI smart contract escrow will automatically release the funds.`
        );

        return res.status(200).json({
          result: {
            success: true,
            message: `Tool executed successfully. PR created at ${pr.html_url}`
          }
        });
      } catch (error) {
        console.error('Execution Error:', error);
        return res.status(500).json({ error: "Failed to execute tool" });
      }

    default:
      return res.status(400).json({ error: "Method not supported" });
  }
});

module.exports = router;
